// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.1
// source: proto/user_auth.proto

package pb

import (
	"demo-service/services/auth/entity"
	reflect "reflect"
	"strings"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Token represents a JWT token and its expiration details.
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                           // The JWT token string.
	ExpiredIn     int32                  `protobuf:"varint,2,opt,name=expired_in,json=expiredIn,proto3" json:"expired_in,omitempty"` // Expiration time in seconds.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_user_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_user_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Token) GetExpiredIn() int32 {
	if x != nil {
		return x.ExpiredIn
	}
	return 0
}

// TokenResponse represents the response containing access and refresh tokens.
type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *Token                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // The access token.
	RefreshToken  *Token                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // The refresh token (optional).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_user_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetAccessToken() *Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *TokenResponse) GetRefreshToken() *Token {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

// AuthRegister represents user registration details.
type AuthRegister struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FirstName         string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`                           // User's first name.
	LastName          string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`                              // User's last name.
	AuthEmailPassword *AuthEmailPassword     `protobuf:"bytes,3,opt,name=auth_email_password,json=authEmailPassword,proto3" json:"auth_email_password,omitempty"` // Authentication details.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthRegister) Reset() {
	*x = AuthRegister{}
	mi := &file_proto_user_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegister) ProtoMessage() {}

func (x *AuthRegister) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegister.ProtoReflect.Descriptor instead.
func (*AuthRegister) Descriptor() ([]byte, []int) {
	return file_proto_user_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRegister) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AuthRegister) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AuthRegister) GetAuthEmailPassword() *AuthEmailPassword {
	if x != nil {
		return x.AuthEmailPassword
	}
	return nil
}

// AuthEmailPassword represents user authentication details using email and password.
type AuthEmailPassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // User's email address.
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // User's password.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEmailPassword) Reset() {
	*x = AuthEmailPassword{}
	mi := &file_proto_user_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEmailPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEmailPassword) ProtoMessage() {}

func (x *AuthEmailPassword) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEmailPassword.ProtoReflect.Descriptor instead.
func (*AuthEmailPassword) Descriptor() ([]byte, []int) {
	return file_proto_user_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthEmailPassword) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthEmailPassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LogoutRequest represents a logout request with the access token to be revoked.
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // The access token to be blacklisted.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_user_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// RefreshTokenRequest represents a refresh token request.
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // The refresh token to exchange for new tokens.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_user_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_proto_user_auth_proto protoreflect.FileDescriptor

const file_proto_user_auth_proto_rawDesc = "" +
	"\n" +
	"\x15proto/user_auth.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"<\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expired_in\x18\x02 \x01(\x05R\texpiredIn\"m\n" +
	"\rTokenResponse\x12,\n" +
	"\faccess_token\x18\x01 \x01(\v2\t.pb.TokenR\vaccessToken\x12.\n" +
	"\rrefresh_token\x18\x02 \x01(\v2\t.pb.TokenR\frefreshToken\"\x91\x01\n" +
	"\fAuthRegister\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12E\n" +
	"\x13auth_email_password\x18\x03 \x01(\v2\x15.pb.AuthEmailPasswordR\x11authEmailPassword\"E\n" +
	"\x11AuthEmailPassword\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken2\xeb\x01\n" +
	"\x0fUserAuthService\x121\n" +
	"\x05Login\x12\x15.pb.AuthEmailPassword\x1a\x11.pb.TokenResponse\x124\n" +
	"\bRegister\x12\x10.pb.AuthRegister\x1a\x16.google.protobuf.Empty\x123\n" +
	"\x06Logout\x12\x11.pb.LogoutRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\fRefreshToken\x12\x17.pb.RefreshTokenRequest\x1a\x11.pb.TokenResponseB\x05Z\x03pb/b\x06proto3"

var (
	file_proto_user_auth_proto_rawDescOnce sync.Once
	file_proto_user_auth_proto_rawDescData []byte
)

func file_proto_user_auth_proto_rawDescGZIP() []byte {
	file_proto_user_auth_proto_rawDescOnce.Do(func() {
		file_proto_user_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_auth_proto_rawDesc), len(file_proto_user_auth_proto_rawDesc)))
	})
	return file_proto_user_auth_proto_rawDescData
}

var file_proto_user_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_user_auth_proto_goTypes = []any{
	(*Token)(nil),               // 0: pb.Token
	(*TokenResponse)(nil),       // 1: pb.TokenResponse
	(*AuthRegister)(nil),        // 2: pb.AuthRegister
	(*AuthEmailPassword)(nil),   // 3: pb.AuthEmailPassword
	(*LogoutRequest)(nil),       // 4: pb.LogoutRequest
	(*RefreshTokenRequest)(nil), // 5: pb.RefreshTokenRequest
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_proto_user_auth_proto_depIdxs = []int32{
	0, // 0: pb.TokenResponse.access_token:type_name -> pb.Token
	0, // 1: pb.TokenResponse.refresh_token:type_name -> pb.Token
	3, // 2: pb.AuthRegister.auth_email_password:type_name -> pb.AuthEmailPassword
	3, // 3: pb.UserAuthService.Login:input_type -> pb.AuthEmailPassword
	2, // 4: pb.UserAuthService.Register:input_type -> pb.AuthRegister
	4, // 5: pb.UserAuthService.Logout:input_type -> pb.LogoutRequest
	5, // 6: pb.UserAuthService.RefreshToken:input_type -> pb.RefreshTokenRequest
	1, // 7: pb.UserAuthService.Login:output_type -> pb.TokenResponse
	6, // 8: pb.UserAuthService.Register:output_type -> google.protobuf.Empty
	6, // 9: pb.UserAuthService.Logout:output_type -> google.protobuf.Empty
	1, // 10: pb.UserAuthService.RefreshToken:output_type -> pb.TokenResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_auth_proto_init() }
func file_proto_user_auth_proto_init() {
	if File_proto_user_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_auth_proto_rawDesc), len(file_proto_user_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_auth_proto_goTypes,
		DependencyIndexes: file_proto_user_auth_proto_depIdxs,
		MessageInfos:      file_proto_user_auth_proto_msgTypes,
	}.Build()
	File_proto_user_auth_proto = out.File
	file_proto_user_auth_proto_goTypes = nil
	file_proto_user_auth_proto_depIdxs = nil
}

func (ad *AuthEmailPassword) Validate() error {
	ad.Email = strings.TrimSpace(ad.Email)

	if !entity.EmailIsValid(ad.Email) {
		return entity.ErrEmailIsNotValid
	}

	ad.Password = strings.TrimSpace(ad.Password)

	if err := entity.CheckPassword(ad.Password); err != nil {
		return err
	}

	return nil
}

func CheckAuthEmail(s *AuthRegister) error {
	if s.AuthEmailPassword == nil {
		return entity.ErrEmailPasswordIsEmpty
	}

	return nil
}

func (ar *AuthRegister) Validate() error {

	if err := CheckAuthEmail(ar); err != nil {
		return err
	}

	if err := ar.AuthEmailPassword.Validate(); err != nil {
		return err
	}

	ar.FirstName = strings.TrimSpace(ar.FirstName)

	if err := entity.CheckFirstName(ar.FirstName); err != nil {
		return err
	}

	ar.LastName = strings.TrimSpace(ar.LastName)

	if err := entity.CheckLastName(ar.LastName); err != nil {
		return err
	}

	return nil
}